name: CI

on: push
jobs:
  build:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.3.3"]
        cabal: ["3.4.0.0"]
        ghc: ["8.10.2"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'source'

    - name: Setup Haskell Stack
      uses: actions/setup-haskell@v1.1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        stack-version: ${{ matrix.stack }}

    - name: Cache stack modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.stack
          ./.stack-work
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Build
      run: stack build --system-ghc

    - name: Deploy to html branch
      run: |
        git config --global user.email robots@github.com
        git config --global user.name GitHub
        stack exec site rebuild

        # if the branch you deploy on is the default branch of the repo, use the below
        # git reset --hard origin/default_branch
        # git pull --rebase
        # else if deploying to a branch that is not the default branch, use
        git fetch
        git checkout origin/html

        # Overwrite existing files with new files
        cp -a _site/. .
        #  Commit
        git add --all
        git commit -m "[`date '+%F %T %Z'`] New release"
        # Push
        git push origin html:html

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     container:
#       image: futtetennista/hakyll:4.12.5.1

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           ref: 'source'

#       - name: Cache stack modules
#         uses: actions/cache@v2
#         with:
#           path: |
#             ~/.stack
#             # /root/.local/bin/stack
#             ./.stack-work
#           key: ${{ runner.os }}-{{ hashFiles('**/website.cabal') }}-stack

#       - name: Get root access
#         run: apt update && apt install sudo

#       - name: Build
#         run: |
#           sudo /root/.local/bin/stack setup
#           sudo /root/.local/bin/stack build
#           sudo /root/.local/bin/stack exec site build
#         # sudo /root/.local/bin/stack build --install-ghc
#         # exec site -- rebuild
#         #  && stack init && stack build

      # - name: Deploy to master branch
      #   run: |
      #     sudo git config --global user.email robots@github.com
      #     sudo git config --global user.name GitHub
      #     sudo /root/.local/bin/stack exec site rebuild
      #     git checkout master
      #     git reset --hard origin/master
      #     git pull --rebase
      #     # Overwrite existing files with new files
      #     cp -a _site/. .
      #     #  Commit
      #     git add --all
      #     git commit -m "[`date '+%F %T %Z'`] New release"
      #     # Push
      #     git push origin master:master



