name: CLI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: futtetennista/hakyll:4.12.5.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'source'

      - name: Cache stack modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            # /root/.local/bin/stack
            ./.stack-work
          key: ${{ runner.os }}-{{ hashFiles('**/website.cabal') }}-stack

      - name: Get root access
        run: apt update && apt install sudo

      - name: Build
        run: /root/.local/bin/stack setup --allow-different-user && /root/.local/bin/stack build && /root/.local/bin/stack exec site build
        # sudo /root/.local/bin/stack build --install-ghc
        # exec site -- rebuild
        #  && stack init && stack build

      - name: Deploy to master branch
        run: |
          su
          git config --global user.email robots@github.com
          git config --global user.name GitHub
          stack exec site rebuild
          git checkout master
          git reset --hard origin/master
          git pull --rebase
          # Overwrite existing files with new files
          cp -a _site/. .
          #  Commit
          git add --all
          git commit -m "[`date '+%F %T %Z'`] New release"
          # Push
          git push origin master:master



